In [ ]:
# Python Library


  A collection of modules that are linked together is also known as a Python library. It has code bundles that can be used again and again in different programs. For programmers, it makes Python programming easier and simpler. Since then, we will not need to compose the same code for various projects.

In [1]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

In [ ]:
v = np.zeros(10)
print(v)

In [ ]:
print('%d bytes' % (v.size * v.itemsize))

In [ ]:
v = np.zeros(10)
v[4] = 1
print(v)

In [ ]:
v = np.arange(10,20)
print(v)

In [ ]:
v = np.arange(10,50)
print(v)
print(type(v))

In [11]:
v = np.arange(50)
print(v)
v = v[::-1]
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [15]:
v = np.arange(9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
nz = np.nonzero([1,0,0,0,0,0,0,0,0,0,0,0,5,3,0,5,4,3,3,2,45,0,0,0,5])
print(nz)

(array([ 0, 12, 13, 15, 16, 17, 18, 19, 20, 24]),)


In [ ]:
from numpy.core.shape_base import vstack
v  = np.eye(5)
print(v)

In [ ]:
v = np.random.random((10,10,10))
print(v)

In [ ]:
v = np.random.random((10,10))
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

In [30]:
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)

0.48208189415900443


In [33]:
v = np.ones((10,10))
#print(v)
v[1:-1, 1:-1] = 0 # first 1:-1 is row and second 1:-1 is column
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [37]:
v = np.zeros((10,10))
#print(v)
v[1:-1, 1:-1] = 1 # first 1:-1 is row and second 1:-1 is column

print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
v = np.ones((5,5))
print(v)
v = np.pad(v, pad_width=1, mode='constant', constant_values='0')
print(v)

In [ ]:
np.nan

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

In [ ]:
# Create a 5x5 matrix with values 1,2,3,4

# *   List item
# *   List item

# just below the diagonal
# v = np.num((5,5))
# num = num +1

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the matrix diagonal with values 1, 2, 3, 4, and 5
values = [1, 2, 3, 4, 5]
np.fill_diagonal(matrix, values)

print(matrix)

In [ ]:
z = np.diag(1+np.arange(4), k =-1) # number of rows stays the same but colums change
print(z)